name: Docker Image CI

on:
    release:
        types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ericvolp12/gohome
        dockerfile: build/gohome.Dockerfile
        tag_with_ref: true
        push: ${{ startsWith(github.ref, 'refs/tags/') }}